### ISSUE TITLE
Serious performance regression when using GHC 8.2.1 + Text.RE.TDFA + Data.Text.Lazy

### ISSUE THREAD

**Issue by ntc2** [iconnect/regex#156] opened 2017-11-22 22:33 UTC
This appears to be a GHC bug, not a bug in the regex packages themselves, but reporting here also in case anyone else runs into this issue. I reported against GHC [here](https://ghc.haskell.org/trac/ghc/ticket/13745#comment:18).

Details
---------

In GHC 8.2.1, I observe apparently exponential time in the length of
the file when matching a simple regex using `Text.Regex.TDFA` and
`Data.Text.Lazy`. And this is a Heisenbug, in that the performance
problem goes away if I build with profiling support! The problem is
not present in GHC 8.0.2, or when using `String` or strict
`Data.Text`.

For the problematic combination, the run times are 3s, 10s, 22s, and 40s
for counting regex matches in files with 10000,
20000, 30000, and 40000 lines, respectively. For all of the
unproblematic combinations, the run time is always about 1s.

[Repo with test code illustrating the problem](https://github.com/ntc2/ghc-8.2.1-regex-lazy-text-bug).

**Comment by saurabhnanda** [comment] 2018-07-19 17:32
@ntc2 are you observing this problem with GHC 8.4.x branch as well?

**Comment by ntc2** [comment] 2018-07-26 17:24
@saurabhnanda Yes. I just tried with GHC 8.4.3 and it's just as slow. I had to change the deps a bit to build [my example code](https://github.com/ntc2/ghc-8.2.1-regex-lazy-text-bug). I ended up with

```
    base-compat-0.10.4
    hashable-1.2.7.0
    regex-base-0.93.2
    regex-pcre-builtin-0.94.4.8.8.35
    regex-tdfa-1.2.3.1
    regex-tdfa-text-1.0.0.3
    time-locale-compat-0.1.1.4
    unordered-containers-0.2.9.0
    utf8-string-1.0.1.1
    regex-1.0.1.3
```

Note that GHC Trac user tdammers investigated this issue and determined it was caused by a bug in the `text` library, not by GHC itself: https://github.com/haskell/text/issues/216.

**Comment by cdornan** [comment] 2018-12-14 14:01
As this is not an issue with regex itself I am closing this issue.  The issue is present though closed, and can still be cross-referenced.

**Closed by cdornan** 2018-12-14 14:01 UTC
